"""Forward imaging, thermodynamics, and observable-reconstruction models."""

__version__ = "1.1.0"

from .atomic_model import ThomasFermiState, build_thomas_fermi_state, recoil_quantities
from .acquisition import (
    RawElectronFrame,
    deterministic_raw_electron_frame,
    simulate_intensity_frame,
    simulate_raw_electron_frame,
)
from .atomic_response import (
    BranchScatteringResult,
    ColumnOpticalResponse,
    OpticalBranch,
    PolarisedOpticalResponse,
    branch_summed_scattered_photons_per_atom,
    complex_column_response,
    polarised_optical_response_from_config,
)
from .camera import (
    add_camera_noise,
    bin_to_camera_pixels,
    centered_camera_shape,
    normalize_camera_counts,
    resample_to_camera_pixels,
    simulate_camera_image,
    simulate_noisy_camera_image,
)
from .dipolar_tf import (
    DipolarThomasFermiState,
    build_dipolar_thomas_fermi_state,
    ellipsoid_demagnetisation_factors,
    scale_dipolar_thomas_fermi_state,
)
from .fourier import propagate_scattered_field
from .imaging import (
    simulate_dgi_image,
    simulate_dgi_object_field,
    simulate_faraday_image,
    simulate_fourier_image,
    simulate_pci_image,
    simulate_pci_object_field,
    simulate_selected_scalar_readout,
)
from .light_atom import (
    dimensionless_detuning,
    faraday_rotation_angle,
    intensity_at_atoms,
    reabsorption_fraction,
    residual_optical_depth,
    scalar_phase_shift,
    scattered_photons_per_atom,
)
from .multishot import accumulate_snr, simulate_multishot_sequence
from .multiframe_thermodynamics import (
    CLASSICAL_HARMONIC_ENERGY_COEFFICIENT,
    FARADAY_ROTATION_FACTOR,
    FARADAY_SCATTERING_FACTOR,
    IDEAL_BOSE_ENERGY_COEFFICIENT,
    OxfordInitialState,
    OxfordMultiframeContract,
    ThermodynamicPulseScattering,
    ThermodynamicSequence,
    ThermodynamicState,
    ThermodynamicExposure,
    anchored_thermal_atoms,
    cadence_status,
    closure_validation_residuals,
    condensate_core_sequence,
    condensate_core_state,
    condensate_core_energy_j,
    measured_scale_non_saturation,
    nominal_critical_atoms,
    oxford_multiframe_contract_from_configs,
    simulate_polarised_thermodynamic_sequence,
    simulate_thermodynamic_sequence,
    solve_state_at_energy,
    thermodynamic_scattering_from_branch_result,
    thermodynamic_exposures,
)
from .multiframe_screening import (
    MultiframeScreenResult,
    ScreenedExposure,
    evaluate_multiframe_screen,
)
from .profiles import thomas_fermi_profile_2d
from .reference_state import (
    CONTACT_TF_CORE,
    POLARISED_DIPOLAR_TF_CORE,
    CondensateCoreState,
    ReferenceState,
    build_model_condensate_core,
    reference_state_from_config,
    reference_states_from_config,
    resolve_model_reference,
    select_reference_condition,
)
__all__ = [
    "__version__",
    "ThomasFermiState",
    "BranchScatteringResult",
    "CONTACT_TF_CORE",
    "ColumnOpticalResponse",
    "CondensateCoreState",
    "DipolarThomasFermiState",
    "CLASSICAL_HARMONIC_ENERGY_COEFFICIENT",
    "FARADAY_ROTATION_FACTOR",
    "FARADAY_SCATTERING_FACTOR",
    "IDEAL_BOSE_ENERGY_COEFFICIENT",
    "OxfordInitialState",
    "OxfordMultiframeContract",
    "MultiframeScreenResult",
    "OpticalBranch",
    "PolarisedOpticalResponse",
    "POLARISED_DIPOLAR_TF_CORE",
    "ReferenceState",
    "RawElectronFrame",
    "ScreenedExposure",
    "ThermodynamicPulseScattering",
    "ThermodynamicSequence",
    "ThermodynamicState",
    "ThermodynamicExposure",
    "accumulate_snr",
    "add_camera_noise",
    "bin_to_camera_pixels",
    "centered_camera_shape",
    "build_thomas_fermi_state",
    "build_dipolar_thomas_fermi_state",
    "build_model_condensate_core",
    "branch_summed_scattered_photons_per_atom",
    "anchored_thermal_atoms",
    "cadence_status",
    "closure_validation_residuals",
    "condensate_core_sequence",
    "condensate_core_state",
    "condensate_core_energy_j",
    "complex_column_response",
    "evaluate_multiframe_screen",
    "ellipsoid_demagnetisation_factors",
    "normalize_camera_counts",
    "resample_to_camera_pixels",
    "simulate_camera_image",
    "simulate_noisy_camera_image",
    "dimensionless_detuning",
    "deterministic_raw_electron_frame",
    "faraday_rotation_angle",
    "intensity_at_atoms",
    "measured_scale_non_saturation",
    "nominal_critical_atoms",
    "oxford_multiframe_contract_from_configs",
    "polarised_optical_response_from_config",
    "reabsorption_fraction",
    "reference_state_from_config",
    "reference_states_from_config",
    "resolve_model_reference",
    "propagate_scattered_field",
    "recoil_quantities",
    "residual_optical_depth",
    "scalar_phase_shift",
    "scale_dipolar_thomas_fermi_state",
    "scattered_photons_per_atom",
    "simulate_fourier_image",
    "simulate_dgi_image",
    "simulate_dgi_object_field",
    "simulate_faraday_image",
    "simulate_pci_image",
    "simulate_pci_object_field",
    "simulate_selected_scalar_readout",
    "simulate_multishot_sequence",
    "simulate_intensity_frame",
    "simulate_raw_electron_frame",
    "simulate_polarised_thermodynamic_sequence",
    "simulate_thermodynamic_sequence",
    "solve_state_at_energy",
    "thermodynamic_scattering_from_branch_result",
    "thermodynamic_exposures",
    "thomas_fermi_profile_2d",
    "select_reference_condition",
]
